### ISSUE TITLE
ragavi-gains Incompatible with bokeh==2.0.0

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/ragavi#56]
I noticed this while trying to help debug ragavi. With bokeh==2.0.0 I get:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/cProfile.py", line 161, in <module>
    main()
  File "/usr/lib/python3.6/cProfile.py", line 154, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/usr/lib/python3.6/cProfile.py", line 20, in runctx
    filename, sort)
  File "/usr/lib/python3.6/profile.py", line 64, in runctx
    prof.runctx(statement, globals, locals)
  File "/usr/lib/python3.6/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "/home/jonathan/venvs/ragavienv/bin/ragavi-vis", line 10, in <module>
    from ragavi.visibilities import main
  File "/home/jonathan/ragavi_tests/ragavi/ragavi/visibilities.py", line 20, in <module>
    from datashader.bokeh_ext import InteractiveImage
  File "/home/jonathan/venvs/ragavienv/lib/python3.6/site-packages/datashader/bokeh_ext.py", line 25, in <module>
    from bokeh.embed.notebook import encode_utf8, notebook_content
ImportError: cannot import name 'encode_utf8'
```

Seems to work with bokeh==1.4.0.

**Comment by JSKenyon** [comment]
Workaround is to just downgrade to bokeh==1.4.0. I would suggest adding it to the setup.py.

**Comment by Mulan-94** [comment]
This is now fixed, I removed the dependence `datashader` section that was causing this error. In the process, I also realised that bokeh v2.0.1 causes `ragavi-gains` to crash. I have thus renamed the issue. And frozen bokeh at v1.4.0 until I find a solution :)
